lib/my_tests_web/router.ex
defmodule MyTestsWeb.Router do
  use MyTestsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MyTestsWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/sop", SopController
    resources "/signup", UserController, only: [:create, :new]
    get "/sign-in", SessionController, :new
    post "/sign-in", SessionController, :create
    delete "/sign-out", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", MyTestsWeb do
  #   pipe_through :api
  # end
end

lib/my_tests_web/views/layout_view.ex
defmodule MyTestsWeb.LayoutView do
  use MyTestsWeb, :view
end

lib/my_tests_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello MyTests!</title>
   <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">


    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="https://cdn.ckeditor.com/4.12.1/standard-all/ckeditor.js"></script>
  </head>

  <body>
    <div class="container">
      <header class="header">
        <%= if signed_in?(@conn) do %>
          <%= link "Sign out", to: session_path(@conn, :delete), method: :delete %>
        <% else %>
          <%= link "Sign In", to: session_path(@conn, :new) %>
          |
          <%= link "Sign up", to: user_path(@conn, :new) %>
        <% end %>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->


</body>
</html>